"""
Achilleas Thomas (Achi-lleas) 02/13/2025:
This is a script that finds the 3 best JSON seeds #0 generated by AlphaFold3 for the same protein-scaffold interaction (judging based on the ipTM).
After the 3 best seeds for every scaffold have been moved to the same directory, they will be superimposed on ChimeraX for analysis of their paratope.
"""

import json, os

def main(prefix):

    if prefix == "bl": # The prefix of the files and the value of n can change for different applications.
        n = 12
    
    elif prefix == "mc":
        n = 26

    for i in range(1,n+1):
        
        os.mkdir(f"./Best seeds/{prefix}{i}") # The file paths, the file names and other parameters can change for different applications of this script.

        iptm_scores = {}

        for j in range(1,21): # Since twenty models have been generated for each scaffold.
        
            with open(f"./Scaffold files/{prefix}{i}seed{j}/fold_{prefix}{i}seed{j}_summary_confidences_0.json", "r") as confidence_metrics:
                
                file_path = f"./Scaffold files/{prefix}{i}seed{j}/fold_{prefix}{i}seed{j}_summary_confidences_0.json"
                structure_name = file_path.split("/")[-2]
                data = json.load(confidence_metrics)
                iptm_scores[structure_name] = data["iptm"]

            best_structures = []

        for iptm in sorted(iptm_scores.values())[-3:]:

            for key, value in iptm_scores.items():
                
                if str(value) == str(iptm) and key not in best_structures:
                    best_structures.append(key)
                    break
                
        for k in best_structures:    

            os.replace(f"./Scaffold files/{k}/fold_{k}_model_0.cif", f"./Best seeds/{prefix}{i}/fold_{k}_model_0.cif")

if __name__ == "__main__":  
    
    main("bl")
    main("mc")
