"""
Achilleas Thomas (Achi-lleas) 02/17/2025:
This is a simple script that will be used to transfer all the .cif files of the 20 seeds #0 generated by AlphaFold3 for each of the Blanchard and McConnell scaffolds into a new directory. 
The .cif files will then be overlaid on ChimeraX using a different script. Instead of this Python script, a Linux script could have been used without difference.
"""

import os

def main(prefix):

    if prefix == "bl": # The numbers and prefixes can change for different applications of this script.
        n = 12
    
    elif prefix == "mc":
        n = 26 

    for scaffold_number in range(1, n+1):

        os.mkdir(f"./cif files/{prefix}{scaffold_number}") # The file paths and other parameeters can change.

        for seed_number in range(1,21): # 20 seeds have been generated for each scaffold.

            os.replace(f"./Models/bl{scaffold_number}seed{seed_number}/fold_bl{scaffold_number}seed{seed_number}_model_0.cif", 
                       f"./cif files/{prefix}{scaffold_number}/fold_bl{scaffold_number}seed{seed_number}_model_0.cif")

if __name__ == "__main__":

    main("bl")
    main("mc")
